export const departments = [
  {
    id: 1,
    name: 'Web Development',
    description: 'Responsible for developing and maintaining web applications.',
    employees: [
      {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        phone: '1234567890',
        dateOfJoin: '2022-01-01',
        dateOfBirth: '1990-05-15',
        salary: 50000,
        role: 'Web Developer',
        gender: 'Male',
        email: 'johndoe@example.com',
      },
      {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        phone: '9876543210',
        dateOfJoin: '2022-02-01',
        dateOfBirth: '1992-08-20',
        salary: 60000,
        role: 'Front-end Developer',
        gender: 'Female',
        email: 'janesmith@example.com',
      },
      // Add more employees
    ],
  },
  {
    id: 2,
    name: 'Network Administration',
    description: 'Responsible for managing and maintaining the company\'s network infrastructure.',
    employees: [
      {
        id: 3,
        firstName: 'Mike',
        lastName: 'Johnson',
        phone: '1112223333',
        dateOfJoin: '2022-03-01',
        dateOfBirth: '1988-11-12',
        salary: 70000,
        role: 'Network Administrator',
        gender: 'Male',
        email: 'mikejohnson@example.com',
      },
      {
        id: 4,
        firstName: 'Sarah',
        lastName: 'Thompson',
        phone: '4445556666',
        dateOfJoin: '2022-04-01',
        dateOfBirth: '1991-02-25',
        salary: 80000,
        role: 'Network Engineer',
        gender: 'Female',
        email: 'sarahthompson@example.com',
      },
      // Add more employees
    ],
  },
  {
    id: 3,
    name: 'Database Administration',
    description: 'Responsible for managing and maintaining the company\'s databases.',
    employees: [
      {
        id: 5,
        firstName: 'David',
        lastName: 'Wilson',
        phone: '5556667777',
        dateOfJoin: '2022-05-01',
        dateOfBirth: '1993-04-10',
        salary: 70000,
        role: 'Database Administrator',
        gender: 'Male',
        email: 'davidwilson@example.com',
      },
      {
        id: 6,
        firstName: 'Emily',
        lastName: 'Brown',
        phone: '8889990000',
        dateOfJoin: '2022-06-01',
        dateOfBirth: '1990-12-05',
        salary: 75000,
        role: 'Database Analyst',
        gender: 'Female',
        email: 'emilybrown@example.com',
      },
      // Add more employees
    ],
  },
  {
    id: 4,
    name: 'UI/UX Design',
    description: 'Responsible for creating intuitive and user-friendly interfaces.',
    employees: [
      {
        id: 7,
        firstName: 'Daniel',
        lastName: 'Clark',
        phone: '2223334444',
        dateOfJoin: '2022-07-01',
        dateOfBirth: '1992-09-18',
        salary: 60000,
        role: 'UI Designer',
        gender: 'Male',
        email: 'danielclark@example.com',
      },
      {
        id: 8,
        firstName: 'Olivia',
        lastName: 'Davis',
        phone: '7778889999',
        dateOfJoin: '2022-08-01',
        dateOfBirth: '1994-06-30',
        salary: 65000,
        role: 'UX Designer',
        gender: 'Female',
        email: 'oliviadavis@example.com',
      },
      // Add more employees
    ],
  },
  {
    id: 5,
    name: 'Quality Assurance',
    description: 'Responsible for ensuring the quality of software products.',
    employees: [
      {
        id: 9,
        firstName: 'William',
        lastName: 'Adams',
        phone: '6667778888',
        dateOfJoin: '2022-09-01',
        dateOfBirth: '1991-07-03',
        salary: 55000,
        role: 'QA Analyst',
        gender: 'Male',
        email: 'williamadams@example.com',
      },
      {
        id: 10,
        firstName: 'Sophia',
        lastName: 'Wilson',
        phone: '3334445555',
        dateOfJoin: '2022-10-01',
        dateOfBirth: '1993-10-22',
        salary: 60000,
        role: 'Software Tester',
        gender: 'Female',
        email: 'sophiawilson@example.com',
      },
      // Add more employees
    ],
  },
  {
    id: 6,
    name: 'Project Management',
    description: 'Responsible for planning, coordinating, and executing projects.',
    employees: [
      {
        id: 11,
        firstName: 'James',
        lastName: 'Johnson',
        phone: '9990001111',
        dateOfJoin: '2022-11-01',
        dateOfBirth: '1989-03-08',
        salary: 90000,
        role: 'Project Manager',
        gender: 'Male',
        email: 'jamesjohnson@example.com',
      },
      {
        id: 12,
        firstName: 'Abigail',
        lastName: 'Taylor',
        phone: '4445556666',
        dateOfJoin: '2022-12-01',
        dateOfBirth: '1990-07-17',
        salary: 85000,
        role: 'Project Coordinator',
        gender: 'Female',
        email: 'abigailtaylor@example.com',
      },
      // Add more employees
    ],
  },
];
